import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About-Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Inquirio Team
        </h1>

        <p className={styles.description}>
          {/* <code className={styles.code}></code> */}
        </p>

        <div className={styles.grid}>

          <a href="https://docs.google.com/document/d/1DZuzvBqMAXCIbWzTuppRrPyWIgN84WahFDxqePfmmis/edit#heading=h.lxy71ra1xeau" className={styles.card}>
            <h2 className={styles.title} >Branden Ge</h2 >
            <h3><li>Software Developer</li></h3>
            <Image
              src='/Branden.jpg' alt='gene' width={250} height={250} />
            <p>
              Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API
            </p>
          </a>

          <a href="https://docs.google.com/document/d/1GJ7ECI5ogCcPMtEcg75w2zh37m-WdiFMVMr_wRYaqI8/edit?usp=sharing" className={styles.card}>
            <h2 className={styles.title} >Brandon Pitts</h2>
            <h3><li>Software Developer</li></h3>
            <Image
              src='/Brandon.jpg' alt='gene' width={250} height={250} />
            <p>
              Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API
            </p>
          </a>

          <a href="https://docs.google.com/document/d/1GJ7ECI5ogCcPMtEcg75w2zh37m-WdiFMVMr_wRYaqI8/edit?usp=sharing" className={styles.card}>
            <h2 className={styles.title} >Daniel Frey</h2>
            <h3><li>Software Developer</li></h3>
            <Image
              src='/Daniel.jpg' alt='gene' width={250} height={250} />
            <p>
              Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API
            </p>
          </a>

          <a href="https://docs.google.com/document/d/1GJ7ECI5ogCcPMtEcg75w2zh37m-WdiFMVMr_wRYaqI8/edit?usp=sharing" className={styles.card}>
            <h2 className={styles.title} >Keelen Fisher</h2>
            <h3><li>Software Developer</li></h3>
            <Image
              src='/Keelen.jpg' alt='gene' width={250} height={250} />
            <p>
              Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API
            </p>
          </a>

          <a href="https://docs.google.com/document/d/1GJ7ECI5ogCcPMtEcg75w2zh37m-WdiFMVMr_wRYaqI8/edit?usp=sharing" className={styles.card}>
            <h2 className={styles.title} >Stephanie Hill</h2>
            <h3><li>Software Developer</li></h3>
            <Image
              src='/Stephanie.jpg' alt='gene' width={250} height={250} />
            <p>
              Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a href="https://docs.google.com/document/d/1GJ7ECI5ogCcPMtEcg75w2zh37m-WdiFMVMr_wRYaqI8/edit?usp=sharing" className={styles.card}>
            <h2 className={styles.title} >Timothee Odushina</h2>
            <h3><li>Software Developer</li></h3>
            <Image
              src='/Timothee.jpg' alt='gene' width={250} height={250} />
            <p>
              Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API.Find in-depth information about Next.js features and API
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        </a>
      </footer>
    </div>
  )
}
